### ISSUE TITLE
button next could be on the right part

### ISSUE THREAD

**Issue by Elisa-cf** [vmalep/witty#34]
hey! great job guys! so as a user when I play specially with the phone I found confusing that the button "next" is on the left and not on the right. I think the logic there should be on the right to give a better user experience because is known that the eyes  are going to find the buttons, menus, etc on the right. I've actually clicked by accident the first time on the exit thinking that was the next. And also when you hold the phone I think is easier because you press the button with the fat finger.

**Comment by vmalep** [comment]
Ok. It has been modified.
